version: 2

workflows:
  version: 2
  workflow:
    jobs:
      - test-2.7
      - test-3.6
      - test-3.7
      - test-3.8

defaults: &defaults
  working_directory: ~/code
  steps:
  - checkout
  - run:
      name: Install dependencies
      command: |
        sudo ln -s ~/.ssh /root/.ssh
        sudo pip install --no-deps -r requirements_tests.txt
        sudo pip install flake8 flake8-import-order pep8-naming
  - run:
      name: Lint
      command: flake8
  - run:
      name: Test
      command: PYTHONPATH=. pytest

jobs:
  test-2.7:
    <<: *defaults
    docker:
    - image: circleci/python:2.7
  test-3.6:
    <<: *defaults
    docker:
    - image: circleci/python:3.6
  test-3.7:
    <<: *defaults
    docker:
    - image: circleci/python:3.7
  test-3.8:
    <<: *defaults
    docker:
    - image: circleci/python:3.8
